apiVersion: rbac.authorization.k8s.io/v1
kind: {{- if .Values.clusterScoped }} ClusterRole {{ else }} Role {{- end }}
metadata:
  name: {{ include "github-actions-runner-operator.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners/status
  verbs:
  - get
  - patch
  - update
# permissions to do leader election.
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - delete
  - patch
  - list
  - update
