{{- if and .Values.githubapp.enabled (not .Values.githubapp.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "github-actions-runner-operator.fullname" . }}
  labels: {{- include "github-actions-runner-operator.labels" . | nindent 4 }}
stringData:
  GITHUB_APP_INTEGRATION_ID: {{ .Values.githubapp.integrationId | quote }}
data:
  GITHUB_APP_PRIVATE_KEY: |-
    {{ .Values.githubapp.privateKey | b64enc }}
{{- end }}
