{{- if .Values.database.external.enabled -}}
{{- if .Values.database.external.databaseUserPassword.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.external.databaseUserPassword.secretName }} 
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.external.databaseUserPassword.secretKey }}: {{ .Values.database.external.databaseUserPassword.secretValue }}
{{- end -}}
{{- end -}}
