apiVersion: rbac.authorization.k8s.io/v1
kind: {{- if eq .Values.namespaced true }} RoleBinding {{- else }} ClusterRoleBinding {{- end }}
metadata:
  name: {{ include "common.names.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{- if eq .Values.namespaced true }} Role {{- else }} ClusterRole {{- end }}
  name: {{ include "common.names.name" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "spring-boot-admin.serviceAccountName" . }}
